package Text::Txt2tags::Tags;

# txt2tags - tag strings per output target
# Port of txt2tags3_mod/tags.py to Perl 5
#
# Convention (same as Python original):
#   \a  – placeholder for the current text inside the mark
#   ~A~ – image/table alignment expansion
#   ~B~ – table border expansion
#   ~S~ – cell colspan expansion
#   ~C~ – column alignment expansion

use strict;
use warnings;
use Exporter 'import';

our $VERSION = '3.9.0';

use Text::Txt2tags::Constants qw(%AA %RST %CSV);

# All tag key names (used to zero-initialise the returned hash)
my @TAG_KEYS = split ' ', <<'END';
    title1              numtitle1
    title2              numtitle2
    title3              numtitle3
    title4              numtitle4
    title5              numtitle5
    title1Open          title1Close
    title2Open          title2Close
    title3Open          title3Close
    title4Open          title4Close
    title5Open          title5Close
    blocktitle1Open     blocktitle1Close
    blocktitle2Open     blocktitle2Close
    blocktitle3Open     blocktitle3Close

    paragraphOpen       paragraphClose
    blockVerbOpen       blockVerbClose      blockVerbLine
    blockQuoteOpen      blockQuoteClose     blockQuoteLine
    blockVerbSep
    blockCommentOpen    blockCommentClose

    fontMonoOpen        fontMonoClose
    fontBoldOpen        fontBoldClose
    fontItalicOpen      fontItalicClose
    fontUnderlineOpen   fontUnderlineClose
    fontStrikeOpen      fontStrikeClose

    listOpen            listClose
    listOpenCompact     listCloseCompact
    listItemOpen        listItemClose       listItemLine
    numlistOpen         numlistClose
    numlistOpenCompact  numlistCloseCompact
    numlistItemOpen     numlistItemClose    numlistItemLine
    deflistOpen         deflistClose
    deflistOpenCompact  deflistCloseCompact
    deflistItem1Open    deflistItem1Close
    deflistItem2Open    deflistItem2Close   deflistItem2LinePrefix

    bar1                bar2
    url                 urlMark             urlMarkAnchor       urlImg
    email               emailMark
    img                 imgAlignLeft        imgAlignRight       imgAlignCenter
                        _imgAlignLeft       _imgAlignRight      _imgAlignCenter

    tableOpen           tableClose
    _tableBorder        _tableAlignLeft     _tableAlignCenter
    tableRowOpen        tableRowClose       tableRowSep
    tableTitleRowOpen   tableTitleRowClose
    tableCellOpen       tableCellClose      tableCellSep
    tableTitleCellOpen  tableTitleCellClose tableTitleCellSep
    _tableColAlignLeft  _tableColAlignRight _tableColAlignCenter
    tableCellAlignLeft  tableCellAlignRight tableCellAlignCenter
    _tableCellAlignLeft _tableCellAlignRight _tableCellAlignCenter
    _tableCellAlignLeftBorder _tableCellAlignRightBorder _tableCellAlignCenterBorder
    _tableCellColSpan   tableColAlignSep
    _tableCellColSpanChar tableCellCovered  _tableCellBorder
    _tableCellMulticolOpen
    _tableCellMulticolClose
    tableCellHead       tableTitleCellHead

    bodyOpen            bodyClose
    cssOpen             cssClose
    tocOpen             tocClose            TOC
    anchor
    comment
    pageBreak
    EOD
END

# ---------------------------------------------------------------------------
# Per-target tag tables
# ---------------------------------------------------------------------------

my %ALL_TAGS = (

    # --- Plain text --------------------------------------------------------
    txt => {
        title1          => '  \a',
        title2          => '        \a',
        title3          => '                \a',
        title4          => '                        \a',
        title5          => '                                \a',
        blockQuoteLine  => '        ',
        listItemOpen    => '- ',
        numlistItemOpen => '\a. ',
        bar1            => '\a',
        url             => '\a',
        urlMark         => '\a (\a)',
        email           => '\a',
        emailMark       => '\a (\a)',
        img             => '[\a]',
    },

    # --- ASCII Art ---------------------------------------------------------
    aat => {
        title1          => '\a',
        title2          => '\a',
        title3          => '\a',
        title4          => '\a',
        title5          => '\a',
        blockQuoteLine  => $AA{quote},
        listItemOpen    => $AA{bullet} . ' ',
        numlistItemOpen => '\a. ',
        bar1            => '-' x 72,
        bar2            => '=' x 72,
        url             => '\a',
        urlMark         => '\a[\a]',
        email           => '\a',
        emailMark       => '\a[\a]',
        img             => '[\a]',
        fontBoldOpen    => '*',
        fontBoldClose   => '*',
        fontItalicOpen  => '/',
        fontItalicClose => '/',
        fontUnderlineOpen  => '_',
        fontUnderlineClose => '_',
        fontStrikeOpen  => '-',
        fontStrikeClose => '-',
    },

    # --- HTML --------------------------------------------------------------
    html => {
        paragraphOpen       => '<P>',
        paragraphClose      => '</P>',
        title1              => '<H1~A~>\a</H1>',
        title2              => '<H2~A~>\a</H2>',
        title3              => '<H3~A~>\a</H3>',
        title4              => '<H4~A~>\a</H4>',
        title5              => '<H5~A~>\a</H5>',
        anchor              => ' ID="\a"',
        blockVerbOpen       => '<PRE>',
        blockVerbClose      => '</PRE>',
        blockQuoteOpen      => '<BLOCKQUOTE>',
        blockQuoteClose     => '</BLOCKQUOTE>',
        fontMonoOpen        => '<CODE>',
        fontMonoClose       => '</CODE>',
        fontBoldOpen        => '<B>',
        fontBoldClose       => '</B>',
        fontItalicOpen      => '<I>',
        fontItalicClose     => '</I>',
        fontUnderlineOpen   => '<U>',
        fontUnderlineClose  => '</U>',
        fontStrikeOpen      => '<S>',
        fontStrikeClose     => '</S>',
        listOpen            => '<UL>',
        listClose           => '</UL>',
        listItemOpen        => '<LI>',
        numlistOpen         => '<OL>',
        numlistClose        => '</OL>',
        numlistItemOpen     => '<LI>',
        deflistOpen         => '<DL>',
        deflistClose        => '</DL>',
        deflistItem1Open    => '<DT>',
        deflistItem1Close   => '</DT>',
        deflistItem2Open    => '<DD>',
        bar1                => '<HR NOSHADE SIZE=1>',
        bar2                => '<HR NOSHADE SIZE=5>',
        url                 => '<A HREF="\a">\a</A>',
        urlMark             => '<A HREF="\a">\a</A>',
        email               => '<A HREF="mailto:\a">\a</A>',
        emailMark           => '<A HREF="mailto:\a">\a</A>',
        img                 => '<IMG~A~ SRC="\a" BORDER="0" ALT="">',
        imgEmbed            => '<IMG~A~ SRC="\a" BORDER="0" ALT="">',
        _imgAlignLeft       => ' ALIGN="left"',
        _imgAlignCenter     => ' ALIGN="middle"',
        _imgAlignRight      => ' ALIGN="right"',
        tableOpen           => '<TABLE~A~~B~ CELLPADDING="4">',
        tableClose          => '</TABLE>',
        tableRowOpen        => '<TR>',
        tableRowClose       => '</TR>',
        tableCellOpen       => '<TD~A~~S~>',
        tableCellClose      => '</TD>',
        tableTitleCellOpen  => '<TH~S~>',
        tableTitleCellClose => '</TH>',
        _tableBorder        => ' BORDER="1"',
        _tableAlignCenter   => ' ALIGN="center"',
        _tableCellAlignRight  => ' ALIGN="right"',
        _tableCellAlignCenter => ' ALIGN="center"',
        _tableCellColSpan   => ' COLSPAN="\a"',
        cssOpen             => '<STYLE TYPE="text/css">',
        cssClose            => '</STYLE>',
        comment             => '<!-- \a -->',
        EOD                 => '</BODY></HTML>',
    },

    # --- XHTML (inherits HTML, override as needed) -------------------------
    xhtml => {
        paragraphOpen       => '<p>',
        paragraphClose      => '</p>',
        title1              => '<h1~A~>\a</h1>',
        title2              => '<h2~A~>\a</h2>',
        title3              => '<h3~A~>\a</h3>',
        title4              => '<h4~A~>\a</h4>',
        title5              => '<h5~A~>\a</h5>',
        anchor              => ' id="\a"',
        blockVerbOpen       => '<pre>',
        blockVerbClose      => '</pre>',
        blockQuoteOpen      => '<blockquote>',
        blockQuoteClose     => '</blockquote>',
        fontMonoOpen        => '<code>',
        fontMonoClose       => '</code>',
        fontBoldOpen        => '<b>',
        fontBoldClose       => '</b>',
        fontItalicOpen      => '<i>',
        fontItalicClose     => '</i>',
        fontUnderlineOpen   => '<u>',
        fontUnderlineClose  => '</u>',
        fontStrikeOpen      => '<s>',
        fontStrikeClose     => '</s>',
        listOpen            => '<ul>',
        listClose           => '</ul>',
        listItemOpen        => '<li>',
        listItemClose       => '</li>',
        numlistOpen         => '<ol>',
        numlistClose        => '</ol>',
        numlistItemOpen     => '<li>',
        numlistItemClose    => '</li>',
        deflistOpen         => '<dl>',
        deflistClose        => '</dl>',
        deflistItem1Open    => '<dt>',
        deflistItem1Close   => '</dt>',
        deflistItem2Open    => '<dd>',
        deflistItem2Close   => '</dd>',
        bar1                => '<hr class="light" />',
        bar2                => '<hr class="heavy" />',
        url                 => '<a href="\a">\a</a>',
        urlMark             => '<a href="\a">\a</a>',
        email               => '<a href="mailto:\a">\a</a>',
        emailMark           => '<a href="mailto:\a">\a</a>',
        img                 => '<img~A~ src="\a" border="0" alt=""/>',
        imgEmbed            => '<img~A~ src="\a" border="0" alt=""/>',
        _imgAlignLeft       => ' align="left"',
        _imgAlignCenter     => ' align="middle"',
        _imgAlignRight      => ' align="right"',
        tableOpen           => '<table~A~~B~ cellpadding="4">',
        tableClose          => '</table>',
        tableRowOpen        => '<tr>',
        tableRowClose       => '</tr>',
        tableCellOpen       => '<td~A~~S~>',
        tableCellClose      => '</td>',
        tableTitleCellOpen  => '<th~S~>',
        tableTitleCellClose => '</th>',
        _tableBorder        => ' border="1"',
        _tableAlignCenter   => ' align="center"',
        _tableCellAlignRight  => ' align="right"',
        _tableCellAlignCenter => ' align="center"',
        _tableCellColSpan   => ' colspan="\a"',
        cssOpen             => '<style type="text/css">',
        cssClose            => '</style>',
        comment             => '<!-- \a -->',
        EOD                 => '</body></html>',
    },

    # --- HTML5 (inherits xhtml, overrides below) --------------------------
    html5 => {
        title1Open          => "<section~A~>\n<h1>\\a</h1>",
        title1Close         => '</section>',
        title2Open          => "<section~A~>\n<h2>\\a</h2>",
        title2Close         => '</section>',
        title3Open          => "<section~A~>\n<h3>\\a</h3>",
        title3Close         => '</section>',
        title4Open          => "<section~A~>\n<h4>\\a</h4>",
        title4Close         => '</section>',
        title5Open          => "<section~A~>\n<h5>\\a</h5>",
        title5Close         => '</section>',
        fontBoldOpen        => '<strong>',
        fontBoldClose       => '</strong>',
        fontItalicOpen      => '<em>',
        fontItalicClose     => '</em>',
        fontUnderlineOpen   => '<span class="underline">',
        fontUnderlineClose  => '</span>',
        fontStrikeOpen      => '<del>',
        fontStrikeClose     => '</del>',
        listItemClose       => '</li>',
        numlistItemClose    => '</li>',
        deflistItem2Close   => '</dd>',
        bar1                => '<hr class="light">',
        bar2                => '<hr class="heavy">',
        img                 => '<img~A~ src="\a" alt="">',
        imgEmbed            => '<img~A~ src="\a" alt="">',
        _imgAlignLeft       => ' class="left"',
        _imgAlignCenter     => ' class="center"',
        _imgAlignRight      => ' class="right"',
        tableOpen           => '<table~A~~B~>',
        _tableBorder        => ' class="tableborder"',
        _tableCellAlignRight  => ' class="right"',
        _tableCellAlignCenter => ' class="center"',
        cssOpen             => '<style>',
        tocOpen             => '<nav>',
        tocClose            => '</nav>',
        EOD                 => '</article></body></html>',
    },

    # --- xhtmls overrides (applied on top of xhtml base) -----------------
    xhtmls => {
        fontBoldOpen        => '<strong>',
        fontBoldClose       => '</strong>',
        fontItalicOpen      => '<em>',
        fontItalicClose     => '</em>',
        fontUnderlineOpen   => '<span style="text-decoration:underline">',
        fontUnderlineClose  => '</span>',
        fontStrikeOpen      => '<span style="text-decoration:line-through">',
        fontStrikeClose     => '</span>',
        listItemClose       => '</li>',
        numlistItemClose    => '</li>',
        deflistItem2Close   => '</dd>',
        bar1                => '<hr class="light" />',
        bar2                => '<hr class="heavy" />',
        img                 => '<img style="display: block;~A~" src="\a" alt=""/>',
        imgEmbed            => '<img~A~ src="\a" alt=""/>',
        _imgAlignLeft       => 'margin: 0 auto 0 0;',
        _imgAlignCenter     => 'margin: 0 auto 0 auto;',
        _imgAlignRight      => 'margin: 0 0 0 auto;',
        _tableAlignCenter   => ' style="margin-left: auto; margin-right: auto;"',
        _tableCellAlignRight  => ' style="text-align:right"',
        _tableCellAlignCenter => ' style="text-align:center"',
    },

    # --- wp overrides (applied on top of xhtml base) ----------------------
    wp => {
        bodyOpen            => '',
        bodyClose           => '',
        paragraphOpen       => '',
        paragraphClose      => '',
        comment             => '',
        EOD                 => '',
        listItemClose       => '</li>',
        numlistItemClose    => '</li>',
        deflistItem2Close   => '</dd>',
        bar1                => '<hr>',
        bar2                => '<hr>',
        fontBoldOpen        => '<strong>',
        fontBoldClose       => '</strong>',
        fontItalicOpen      => '<em>',
        fontItalicClose     => '</em>',
        # wp uses HTML-style img (no self-closing /) and no cellpadding in tables
        img                 => '<img~A~ src="\a" border="0" alt="">',
        tableOpen           => '<table~A~~B~>',
    },

    # --- Markdown ----------------------------------------------------------
    md => {
        title1              => '# \a ',
        title2              => '## \a ',
        title3              => '### \a ',
        title4              => '#### \a ',
        title5              => '##### \a ',
        blockVerbLine       => '    ',
        blockQuoteLine      => '> ',
        listItemOpen        => '*',
        listItemLine        => ' ',
        numlistItemOpen     => '1.',
        deflistItem1Open    => ': ',
        bar1                => '---',
        bar2                => '---',
        url                 => '\a',
        urlMark             => '[\a](\a)',
        email               => '\a',
        emailMark           => '[\a](mailto:\a)',
        img                 => '![](\a)',
        fontMonoOpen        => '`',
        fontMonoClose       => '`',
        fontBoldOpen        => '**',
        fontBoldClose       => '**',
        fontItalicOpen      => '*',
        fontItalicClose     => '*',
        fontStrikeOpen      => '~~',
        fontStrikeClose     => '~~',
        tableRowOpen        => '|',
        tableRowClose       => '|',
        tableCellSep        => ' |',
        tableTitleRowOpen   => '| ',
        tableTitleRowClose  => "|\n|---------------|",
        tableTitleCellSep   => ' |',
    },

    # --- reStructuredText -------------------------------------------------
    rst => {
        title1          => '\a',
        title2          => '\a',
        title3          => '\a',
        title4          => '\a',
        title5          => '\a',
        blockVerbOpen   => "::\n",
        blockQuoteLine  => '    ',
        listItemOpen    => $RST{bullet} . ' ',
        numlistItemOpen => '\a. ',
        bar1            => '-' x 10,
        url             => '\a',
        urlMark         => '`\a <\a>`_',
        email           => '\a',
        emailMark       => '`\a <\a>`_',
        img             => "\n\n.. image:: \\a\n   :align: ~A~\n\nENDIMG",
        urlImg          => "\n   :target: ",
        _imgAlignLeft   => 'left',
        _imgAlignCenter => 'center',
        _imgAlignRight  => 'right',
        fontMonoOpen    => '``',
        fontMonoClose   => '``',
        fontBoldOpen    => '**',
        fontBoldClose   => '**',
        fontItalicOpen  => '*',
        fontItalicClose => '*',
        comment         => '.. \a',
        TOC             => "\n.. contents::",
    },

    # --- AsciiDoc ---------------------------------------------------------
    adoc => {
        title1              => '== \a',
        title2              => '=== \a',
        title3              => '==== \a',
        title4              => '===== \a',
        title5              => '===== \a',
        blockVerbOpen       => '----',
        blockVerbClose      => '----',
        deflistItem1Close   => '::',
        deflistClose        => '',
        deflistItem2Open    => "\t",
        deflistItem2LinePrefix => "\t",
        fontMonoOpen        => '+',
        fontMonoClose       => '+',
        fontBoldOpen        => '*',
        fontBoldClose       => '*',
        fontItalicOpen      => '_',
        fontItalicClose     => '_',
        listItemOpen        => ' ',
        listItemLine        => '*',
        numlistItemOpen     => '1. ',
        url                 => '\a',
        urlMark             => '\a[\a]',
        email               => 'mailto:\a',
        emailMark           => 'mailto:\a[\a]',
        img                 => 'image::\a[]',
    },

    # --- LaTeX -------------------------------------------------------------
    tex => {
        title1          => '~A~\section*{\a}',
        title2          => '~A~\subsection*{\a}',
        title3          => '~A~\subsubsection*{\a}',
        title4          => "~A~\\paragraph{}\\textbf{\\a}\\\\\n",
        title5          => "~A~\\paragraph{}\\textbf{\\a}\\\\\n",
        numtitle1       => "\n~A~\\section{\\a}",
        numtitle2       => '~A~\subsection{\a}',
        numtitle3       => '~A~\subsubsection{\a}',
        anchor          => "\\hypertarget{\\a}{}\n",
        blockVerbOpen   => '\begin{verbatim}',
        blockVerbClose  => '\end{verbatim}',
        blockQuoteOpen  => '\begin{quotation}',
        blockQuoteClose => '\end{quotation}',
        fontMonoOpen    => '\texttt{',
        fontMonoClose   => '}',
        fontBoldOpen    => '\textbf{',
        fontBoldClose   => '}',
        fontItalicOpen  => '\textit{',
        fontItalicClose => '}',
        fontUnderlineOpen  => '\underline{',
        fontUnderlineClose => '}',
        fontStrikeOpen  => '\sout{',
        fontStrikeClose => '}',
        listOpen        => '\begin{itemize}',
        listClose       => '\end{itemize}',
        listOpenCompact => '\begin{compactitem}',
        listCloseCompact => '\end{compactitem}',
        listItemOpen    => '\item ',
        numlistOpen     => '\begin{enumerate}',
        numlistClose    => '\end{enumerate}',
        numlistOpenCompact  => '\begin{compactenum}',
        numlistCloseCompact => '\end{compactenum}',
        numlistItemOpen => '\item ',
        deflistOpen     => '\begin{description}',
        deflistClose    => '\end{description}',
        deflistOpenCompact  => '\blistItemOpenegin{compactdesc}',
        deflistCloseCompact => '\end{compactdesc}',
        deflistItem1Open    => '\item[',
        deflistItem1Close   => ']',
        bar1            => '\hrulefill{}',
        bar2            => '\rule{\linewidth}{1mm}',
        url             => '\href{\a}{\a}',
        urlMark         => '\href{\a}{\a}',
        email           => '\href{mailto:\a}{\a}',
        emailMark       => '\href{mailto:\a}{\a}',
        img             => '\includegraphics{\a}',
        tableOpen       => '\begin{center}\begin{tabular}{|~C~|}',
        tableClose      => '\end{tabular}\end{center}',
        tableRowOpen    => '\hline ',
        tableRowClose   => ' \\\\',
        tableCellSep    => ' & ',
        _tableColAlignLeft   => 'l',
        _tableColAlignRight  => 'r',
        _tableColAlignCenter => 'c',
        _tableCellAlignLeft  => 'l',
        _tableCellAlignRight => 'r',
        _tableCellAlignCenter => 'c',
        _tableCellColSpan    => '\a',
        _tableCellMulticolOpen  => '\multicolumn{\a}{|~C~|}{',
        _tableCellMulticolClose => '}',
        tableColAlignSep => '|',
        comment         => '% \a',
        TOC             => '\tableofcontents',
        pageBreak       => '\clearpage',
        EOD             => '\end{document}',
    },

    # --- csv / csvs -------------------------------------------------------
    csv => {
        tableCellSep    => ',',
        tableCellOpen   => '"',
        tableCellClose  => '"',
    },
    csvs => {},   # inherits csv

    # --- txt2t (round-trip) -----------------------------------------------
    txt2t => {
        title1              => '         = \a =~A~',
        title2              => '        == \a ==~A~',
        title3              => '       === \a ===~A~',
        title4              => '      ==== \a ====~A~',
        title5              => '     ===== \a =====~A~',
        numtitle1           => '         + \a +~A~',
        numtitle2           => '        ++ \a ++~A~',
        numtitle3           => '       +++ \a +++~A~',
        numtitle4           => '      ++++ \a ++++~A~',
        numtitle5           => '     +++++ \a +++++~A~',
        anchor              => '[\a]',
        blockVerbOpen       => '```',
        blockVerbClose      => '```',
        blockQuoteLine      => "\t",
        blockCommentOpen    => '%%%',
        blockCommentClose   => '%%%',
        fontMonoOpen        => '``',
        fontMonoClose       => '``',
        fontBoldOpen        => '**',
        fontBoldClose       => '**',
        fontItalicOpen      => '//',
        fontItalicClose     => '//',
        fontUnderlineOpen   => '__',
        fontUnderlineClose  => '__',
        fontStrikeOpen      => '--',
        fontStrikeClose     => '--',
        listItemOpen        => '- ',
        numlistItemOpen     => '+ ',
        deflistItem1Open    => ': ',
        listClose           => '-',
        numlistClose        => '+',
        deflistClose        => ':',
        bar1                => '-------------------------',
        bar2                => '=========================',
        url                 => '\a',
        urlMark             => '[\a \a]',
        email               => '\a',
        emailMark           => '[\a \a]',
        img                 => '[\a]',
        _tableBorder        => '|',
        _tableAlignLeft     => '',
        _tableAlignCenter   => '   ',
        tableRowOpen        => '~A~',
        tableRowClose       => '~B~',
        tableTitleRowOpen   => '~A~|',
        tableCellOpen       => '| ',
        tableCellClose      => ' ~S~',
        tableCellAlignLeft  => '\a  ',
        tableCellAlignRight => '  \a',
        tableCellAlignCenter=> '  \a  ',
        _tableCellColSpanChar => '|',
        comment             => '% \a',
    },

    # --- SGML LinuxDoc --------------------------------------------------------
    sgml => {
        paragraphOpen       => '<p>',
        title1              => '<sect>\a~A~<p>',
        title2              => '<sect1>\a~A~<p>',
        title3              => '<sect2>\a~A~<p>',
        title4              => '<sect3>\a~A~<p>',
        title5              => '<sect4>\a~A~<p>',
        anchor              => '<label id="\a">',
        blockVerbOpen       => '<tscreen><verb>',
        blockVerbClose      => '</verb></tscreen>',
        blockQuoteOpen      => '<quote>',
        blockQuoteClose     => '</quote>',
        fontMonoOpen        => '<tt>',
        fontMonoClose       => '</tt>',
        fontBoldOpen        => '<bf>',
        fontBoldClose       => '</bf>',
        fontItalicOpen      => '<em>',
        fontItalicClose     => '</em>',
        fontUnderlineOpen   => '<bf><em>',
        fontUnderlineClose  => '</em></bf>',
        listOpen            => '<itemize>',
        listClose           => '</itemize>',
        listItemOpen        => '<item>',
        numlistOpen         => '<enum>',
        numlistClose        => '</enum>',
        numlistItemOpen     => '<item>',
        deflistOpen         => '<descrip>',
        deflistClose        => '</descrip>',
        deflistItem1Open    => '<tag>',
        deflistItem1Close   => '</tag>',
        bar1                => '<!-- \a -->',
        url                 => '<htmlurl url="\a" name="\a">',
        urlMark             => '<htmlurl url="\a" name="\a">',
        email               => '<htmlurl url="mailto:\a" name="\a">',
        emailMark           => '<htmlurl url="mailto:\a" name="\a">',
        img                 => '<figure><ph vspace=""><img src="\a"></figure>',
        tableOpen           => '<table><tabular ca="~C~">',
        tableClose          => '</tabular></table>',
        tableRowSep         => '<rowsep>',
        tableCellSep        => '<colsep>',
        _tableColAlignLeft  => 'l',
        _tableColAlignRight => 'r',
        _tableColAlignCenter => 'c',
        comment             => '<!-- \a -->',
        TOC                 => '<toc>',
        EOD                 => '</article>',
    },

    # --- DocBook XML ----------------------------------------------------------
    dbk => {
        paragraphOpen       => '<para>',
        paragraphClose      => '</para>',
        title1Open          => '~A~<sect1><title>\a</title>',
        title1Close         => '</sect1>',
        title2Open          => '~A~  <sect2><title>\a</title>',
        title2Close         => '  </sect2>',
        title3Open          => '~A~    <sect3><title>\a</title>',
        title3Close         => '    </sect3>',
        title4Open          => '~A~      <sect4><title>\a</title>',
        title4Close         => '      </sect4>',
        title5Open          => '~A~        <sect5><title>\a</title>',
        title5Close         => '        </sect5>',
        anchor              => "<anchor id=\"\\a\"/>\n",
        blockVerbOpen       => '<programlisting>',
        blockVerbClose      => '</programlisting>',
        blockQuoteOpen      => '<blockquote><para>',
        blockQuoteClose     => '</para></blockquote>',
        fontMonoOpen        => '<code>',
        fontMonoClose       => '</code>',
        fontBoldOpen        => '<emphasis role="bold">',
        fontBoldClose       => '</emphasis>',
        fontItalicOpen      => '<emphasis>',
        fontItalicClose     => '</emphasis>',
        fontUnderlineOpen   => '<emphasis role="underline">',
        fontUnderlineClose  => '</emphasis>',
        listOpen            => '<itemizedlist>',
        listClose           => '</itemizedlist>',
        listItemOpen        => '<listitem><para>',
        listItemClose       => '</para></listitem>',
        numlistOpen         => '<orderedlist numeration="arabic">',
        numlistClose        => '</orderedlist>',
        numlistItemOpen     => '<listitem><para>',
        numlistItemClose    => '</para></listitem>',
        deflistOpen         => '<variablelist>',
        deflistClose        => '</variablelist>',
        deflistItem1Open    => '<varlistentry><term>',
        deflistItem1Close   => '</term>',
        deflistItem2Open    => '<listitem><para>',
        deflistItem2Close   => '</para></listitem></varlistentry>',
        url                 => '<ulink url="\a">\a</ulink>',
        urlMark             => '<ulink url="\a">\a</ulink>',
        email               => '<email>\a</email>',
        emailMark           => '<email>\a</email>',
        img                 => '<mediaobject><imageobject><imagedata fileref="\a"/></imageobject></mediaobject>',
        tableOpen           => '<informaltable><tgroup cols="n_cols"><tbody>',
        tableClose          => '</tbody></tgroup></informaltable>',
        tableRowOpen        => '<row>',
        tableRowClose       => '</row>',
        tableCellOpen       => '<entry>',
        tableCellClose      => '</entry>',
        tableTitleRowOpen   => '<thead>',
        tableTitleRowClose  => '</thead>',
        _tableBorder        => ' frame="all"',
        _tableAlignCenter   => ' align="center"',
        _tableCellAlignRight   => ' align="right"',
        _tableCellAlignCenter  => ' align="center"',
        _tableCellColSpan   => ' COLSPAN="\a"',
        TOC                 => '<index/>',
        comment             => '<!-- \a -->',
        EOD                 => '</article>',
    },

    # --- Lout -----------------------------------------------------------------
    lout => {
        paragraphOpen       => '@LP',
        blocktitle1Open     => '@BeginSections',
        blocktitle1Close    => '@EndSections',
        blocktitle2Open     => ' @BeginSubSections',
        blocktitle2Close    => ' @EndSubSections',
        blocktitle3Open     => '  @BeginSubSubSections',
        blocktitle3Close    => '  @EndSubSubSections',
        title1Open          => '~A~@Section @Title { \a } @Begin',
        title1Close         => '@End @Section',
        title2Open          => '~A~ @SubSection @Title { \a } @Begin',
        title2Close         => ' @End @SubSection',
        title3Open          => '~A~  @SubSubSection @Title { \a } @Begin',
        title3Close         => '  @End @SubSubSection',
        title4Open          => '~A~@LP @LeftDisplay @B { \a }',
        title5Open          => '~A~@LP @LeftDisplay @B { \a }',
        anchor              => "\@Tag { \\a }\n",
        blockVerbOpen       => '@LP @ID @F @RawVerbatim @Begin',
        blockVerbClose      => '@End @RawVerbatim',
        blockQuoteOpen      => '@QD {',
        blockQuoteClose     => '}',
        fontMonoOpen        => '{@F {',
        fontMonoClose       => '}}',
        fontBoldOpen        => '{@B {',
        fontBoldClose       => '}}',
        fontItalicOpen      => '{@II {',
        fontItalicClose     => '}}',
        fontUnderlineOpen   => '{@Underline{',
        fontUnderlineClose  => '}}',
        listOpen            => '@BulletList',
        listClose           => '@EndList',
        listItemOpen        => '@ListItem{',
        listItemClose       => '}',
        numlistOpen         => '@NumberedList',
        numlistClose        => '@EndList',
        numlistItemOpen     => '@ListItem{',
        numlistItemClose    => '}',
        deflistOpen         => '@TaggedList',
        deflistClose        => '@EndList',
        deflistItem1Open    => '@DropTagItem {',
        deflistItem1Close   => '}',
        deflistItem2Open    => '{',
        deflistItem2Close   => '}',
        bar1                => '@DP @FullWidthRule',
        url                 => '{blue @Colour { \a }}',
        urlMark             => '\a ({blue @Colour { \a }})',
        email               => '{blue @Colour { \a }}',
        emailMark           => '\a ({blue @Colour{ \a }})',
        img                 => '~A~@IncludeGraphic { \a }',
        _imgAlignLeft       => '@LeftDisplay ',
        _imgAlignRight      => '@RightDisplay ',
        _imgAlignCenter     => '@CentredDisplay ',
        tableOpen           => "\@LP\n~A~\@CentredDisplay \@Tbl~B~\n{",
        tableClose          => "\n}",
        tableRowOpen        => "\@Row\n",
        tableTitleRowOpen   => "\@HeaderRow\n",
        tableTitleRowClose  => "\@EndHeaderRow\n",
        tableCellOpen       => '\a { ',
        tableCellClose      => ' }',
        tableTitleCellOpen  => ' { @B { ',
        tableTitleCellClose => ' } }',
        _tableCellAlignRight   => ' indent { right } ',
        _tableCellAlignLeft    => ' indent { left } ',
        _tableCellAlignCenter  => ' indent { ctr } ',
        _tableAlign            => '@CentredDisplay ',
        _tableBorder           => "\nrule {yes}",
        comment             => '# \a',
        TOC                 => '@DP @ContentsGoesHere @DP',
        pageBreak           => '@NP',
        EOD                 => '@End @Text',
    },

    # --- MoinMoin -------------------------------------------------------------
    moin => {
        title1          => '= \a =',
        title2          => '== \a ==',
        title3          => '=== \a ===',
        title4          => '==== \a ====',
        title5          => '===== \a =====',
        blockVerbOpen   => '{{{',
        blockVerbClose  => '}}}',
        blockQuoteLine  => '  ',
        fontMonoOpen    => '{{{',
        fontMonoClose   => '}}}',
        fontBoldOpen    => "'''",
        fontBoldClose   => "'''",
        fontItalicOpen  => "''",
        fontItalicClose => "''",
        fontUnderlineOpen  => '__',
        fontUnderlineClose => '__',
        fontStrikeOpen  => '--(',
        fontStrikeClose => ')--',
        listItemOpen    => ' * ',
        numlistItemOpen => ' \a. ',
        deflistItem1Open  => ' ',
        deflistItem1Close => '::',
        deflistItem2LinePrefix => ' :: ',
        bar1            => '----',
        bar2            => '--------',
        url             => '[[\a]]',
        urlMark         => '[[\a|\a]]',
        email           => '\a',
        emailMark       => '[[mailto:\a|\a]]',
        img             => '{{\a}}',
        tableRowOpen    => '||',
        tableCellOpen   => '~S~~A~ ',
        tableCellClose  => ' ||',
        _tableCellAlignRight  => '<)>',
        _tableCellAlignCenter => '<:>',
        _tableCellColSpanChar => '||',
        comment         => '/* \a */',
        TOC             => '<<TableOfContents>>',
    },

    # --- Google Wiki ----------------------------------------------------------
    gwiki => {
        title1          => '= \a =',
        title2          => '== \a ==',
        title3          => '=== \a ===',
        title4          => '==== \a ====',
        title5          => '===== \a =====',
        blockVerbOpen   => '{{{',
        blockVerbClose  => '}}}',
        blockQuoteLine  => '  ',
        fontMonoOpen    => '{{{',
        fontMonoClose   => '}}}',
        fontBoldOpen    => '*',
        fontBoldClose   => '*',
        fontItalicOpen  => '_',
        fontItalicClose => '_',
        fontStrikeOpen  => '~~',
        fontStrikeClose => '~~',
        listItemOpen    => ' * ',
        numlistItemOpen => ' # ',
        url             => '\a',
        urlMark         => '[\a \a]',
        email           => 'mailto:\a',
        emailMark       => '[mailto:\a \a]',
        img             => '[\a]',
        tableRowOpen    => '|| ',
        tableRowClose   => ' ||',
        tableCellSep    => ' || ',
    },

    # --- DokuWiki -------------------------------------------------------------
    doku => {
        title1          => '===== \a =====',
        title2          => '==== \a ====',
        title3          => '=== \a ===',
        title4          => '== \a ==',
        title5          => '= \a =',
        blockQuoteLine  => '>',
        fontMonoOpen    => "''",
        fontMonoClose   => "''",
        fontBoldOpen    => '**',
        fontBoldClose   => '**',
        fontItalicOpen  => '//',
        fontItalicClose => '//',
        fontUnderlineOpen  => '__',
        fontUnderlineClose => '__',
        fontStrikeOpen  => '<del>',
        fontStrikeClose => '</del>',
        listItemOpen    => '  * ',
        numlistItemOpen => '  - ',
        bar1            => '----',
        url             => '[[\a]]',
        urlMark         => '[[\a|\a]]',
        email           => '[[\a]]',
        emailMark       => '[[\a|\a]]',
        img             => '{{\a}}',
        imgAlignLeft    => '{{\a }}',
        imgAlignRight   => '{{ \a}}',
        imgAlignCenter  => '{{ \a }}',
        tableTitleRowOpen  => '^ ',
        tableTitleRowClose => ' ^',
        tableTitleCellSep  => ' ^ ',
        tableRowOpen    => '| ',
        tableRowClose   => ' |',
        tableCellSep    => ' | ',
    },

    # --- PmWiki ---------------------------------------------------------------
    pmw => {
        title1          => '~A~! \a ',
        title2          => '~A~!! \a ',
        title3          => '~A~!!! \a ',
        title4          => '~A~!!!! \a ',
        title5          => '~A~!!!!! \a ',
        blockQuoteOpen  => '->',
        blockQuoteClose => "\n",
        fontMonoOpen    => '@@',
        fontMonoClose   => '@@',
        fontBoldOpen    => "'''",
        fontBoldClose   => "'''",
        fontItalicOpen  => "''",
        fontItalicClose => "''",
        fontUnderlineOpen  => '{+',
        fontUnderlineClose => '+}',
        fontStrikeOpen  => '{-',
        fontStrikeClose => '-}',
        listItemLine    => '*',
        numlistItemLine => '#',
        deflistItem1Open  => ': ',
        deflistItem1Close => ':',
        blockVerbOpen   => '[@',
        blockVerbClose  => '@]',
        bar1            => '----',
        url             => '\a',
        urlMark         => '[[\a -> \a]]',
        email           => '\a',
        emailMark       => '[[\a -> mailto:\a]]',
        anchor          => "[[#\\a]]\n",
        img             => '\a',
        tableTitleRowOpen  => '||! ',
        tableTitleRowClose => '||',
        tableTitleCellSep  => ' ||!',
        tableRowOpen    => '||',
        tableRowClose   => '||',
        tableCellSep    => ' ||',
    },

    # --- MediaWiki ------------------------------------------------------------
    wiki => {
        title1          => '== \a ==',
        title2          => '=== \a ===',
        title3          => '==== \a ====',
        title4          => '===== \a =====',
        title5          => '====== \a ======',
        blockVerbOpen   => '<pre>',
        blockVerbClose  => '</pre>',
        blockQuoteOpen  => '<blockquote>',
        blockQuoteClose => '</blockquote>',
        fontMonoOpen    => '<tt>',
        fontMonoClose   => '</tt>',
        fontBoldOpen    => "'''",
        fontBoldClose   => "'''",
        fontItalicOpen  => "''",
        fontItalicClose => "''",
        fontUnderlineOpen  => '<u>',
        fontUnderlineClose => '</u>',
        fontStrikeOpen  => '<s>',
        fontStrikeClose => '</s>',
        listItemLine    => '*',
        numlistItemLine => '#',
        deflistItem1Open  => '; ',
        deflistItem2LinePrefix => ': ',
        bar1            => '----',
        url             => '[\a]',
        urlMark         => '[\a \a]',
        urlMarkAnchor   => '[[\a|\a]]',
        email           => 'mailto:\a',
        emailMark       => '[mailto:\a \a]',
        img             => '[[Image:\a~A~]]',
        _imgAlignLeft   => '|left',
        _imgAlignCenter => '|center',
        _imgAlignRight  => '|right',
        tableOpen       => '{|~A~~B~',
        tableClose      => '|}',
        tableRowOpen    => '|-',
        tableTitleRowOpen  => '|-',
        tableCellOpen   => "\n|~A~~S~~Z~ ",
        tableTitleCellOpen => "\n!~A~~S~~Z~ ",
        _tableBorder    => ' border="1"',
        _tableAlignCenter  => ' align="center"',
        _tableCellAlignRight  => ' align="right"',
        _tableCellAlignCenter => ' align="center"',
        _tableCellColSpan => ' colspan="\a"',
        comment         => '<!-- \a -->',
        TOC             => '__TOC__',
    },

    # --- Redmine Wiki ---------------------------------------------------------
    red => {
        title1          => 'h1. \a',
        title2          => 'h2. \a',
        title3          => 'h3. \a',
        title4          => 'h4. \a',
        title5          => 'h5. \a',
        fontBoldOpen    => '*',
        fontBoldClose   => '*',
        fontItalicOpen  => '_',
        fontItalicClose => '_',
        fontStrikeOpen  => '-',
        fontStrikeClose => '-',
        fontUnderlineOpen  => '+',
        fontUnderlineClose => '+',
        blockVerbOpen   => '<pre>',
        blockVerbClose  => '</pre>',
        blockQuoteLine  => 'bq. ',
        fontMonoOpen    => '@',
        fontMonoClose   => '@',
        listItemLine    => '*',
        numlistItemLine => '#',
        deflistItem1Open => '* ',
        url             => '\a',
        urlMark         => '"\a":\a',
        email           => '\a',
        emailMark       => '"\a":\a',
        img             => '!~A~\a!',
        _imgAlignLeft   => '',
        _imgAlignCenter => '=',
        _imgAlignRight  => '>',
        tableTitleCellOpen => '_.',
        tableTitleCellSep  => '|',
        tableCellOpen   => '~S~~A~. ',
        tableCellSep    => '|',
        tableRowOpen    => '|',
        tableRowClose   => '|',
        _tableCellColSpan => '\\\a',
        bar1            => '---',
        bar2            => '---',
        TOC             => '{{toc}}',
    },

    # --- VimWiki --------------------------------------------------------------
    vimwiki => {
        title1          => '= \a =',
        title2          => '== \a ==',
        title3          => '=== \a ===',
        title4          => '==== \a ====',
        title5          => '===== \a =====',
        blockVerbOpen   => '{{{',
        blockVerbClose  => '}}}',
        blockQuoteOpen  => '{{{',
        blockQuoteClose => '}}}',
        fontMonoOpen    => '`',
        fontMonoClose   => '`',
        fontBoldOpen    => ' *',
        fontBoldClose   => '* ',
        fontItalicOpen  => ' _',
        fontItalicClose => '_ ',
        fontStrikeOpen  => ' ~~',
        fontStrikeClose => '~~ ',
        listItemOpen    => '- ',
        listItemLine    => "\t",
        numlistItemOpen => '# ',
        numlistItemLine => "\t",
        bar1            => '----',
        url             => '[\a]',
        urlMark         => '[\a \a]',
        email           => 'mailto:\a',
        emailMark       => '[mailto:\a \a]',
        img             => '[\a]',
        tableRowOpen    => '| ',
        tableRowClose   => ' |',
        tableCellSep    => ' | ',
        comment         => '%% \a',
        TOC             => '%toc',
    },

    # --- MagicPoint -----------------------------------------------------------
    mgp => {
        paragraphOpen   => '%font "normal", size 5',
        title1          => "%page\n\n\\a\n",
        title2          => "%page\n\n\\a\n",
        title3          => "%page\n\n\\a\n",
        title4          => "%page\n\n\\a\n",
        title5          => "%page\n\n\\a\n",
        blockVerbOpen   => '%font "mono"',
        blockVerbClose  => '%font "normal"',
        blockQuoteOpen  => '%prefix "       "',
        blockQuoteClose => '%prefix "  "',
        fontMonoOpen    => "\n%cont, font \"mono\"\n",
        fontMonoClose   => "\n%cont, font \"normal\"\n",
        fontBoldOpen    => "\n%cont, font \"normal-b\"\n",
        fontBoldClose   => "\n%cont, font \"normal\"\n",
        fontItalicOpen  => "\n%cont, font \"normal-i\"\n",
        fontItalicClose => "\n%cont, font \"normal\"\n",
        fontUnderlineOpen  => "\n%cont, fore \"cyan\"\n",
        fontUnderlineClose => "\n%cont, fore \"white\"\n",
        listItemLine    => "\t",
        numlistItemLine => "\t",
        numlistItemOpen => '\a. ',
        deflistItem1Open  => "\t\n%cont, font \"normal-b\"\n",
        deflistItem1Close => "\n%cont, font \"normal\"\n",
        bar1            => '%bar "white" 5',
        bar2            => '%pause',
        url             => "\n%cont, fore \"cyan\"\n\\a\n%cont, fore \"white\"\n",
        urlMark         => "\\a \n%cont, fore \"cyan\"\n\\a\n%cont, fore \"white\"\n",
        email           => "\n%cont, fore \"cyan\"\n\\a\n%cont, fore \"white\"\n",
        emailMark       => "\\a \n%cont, fore \"cyan\"\n\\a\n%cont, fore \"white\"\n",
        img             => "~A~\n%newimage \"\\a\"\n%left\n",
        _imgAlignLeft   => "\n%left",
        _imgAlignRight  => "\n%right",
        _imgAlignCenter => "\n%center",
        comment         => '%% \a',
        pageBreak       => "%page\n\n\n",
        EOD             => '%%EOD',
    },

    # --- man (groff) ----------------------------------------------------------
    man => {
        paragraphOpen   => '.P',
        title1          => '.SH \a',
        title2          => '.SS \a',
        title3          => '.SS \a',
        title4          => '.SS \a',
        title5          => '.SS \a',
        blockVerbOpen   => '.nf',
        blockVerbClose  => ".fi\n",
        blockQuoteOpen  => '.RS',
        blockQuoteClose => '.RE',
        fontBoldOpen    => '\fB',
        fontBoldClose   => '\fR',
        fontItalicOpen  => '\fI',
        fontItalicClose => '\fR',
        listOpen        => '.RS',
        listItemOpen    => ".IP \\(bu 3\n",
        listClose       => ".RE\n.IP",
        numlistOpen     => '.RS',
        numlistItemOpen => '.IP \a. 3\n',
        numlistClose    => ".RE\n.IP",
        deflistItem1Open => ".TP\n",
        bar1            => "\n\n",
        url             => '\a',
        urlMark         => '\a (\a)',
        email           => '\a',
        emailMark       => '\a (\a)',
        img             => '\a',
        tableOpen       => ".TS\n~A~~B~tab(^); ~C~.",
        tableClose      => '.TE',
        tableRowOpen    => ' ',
        tableCellSep    => '^',
        _tableAlignCenter  => 'center, ',
        _tableBorder       => 'allbox, ',
        _tableColAlignLeft  => 'l',
        _tableColAlignRight => 'r',
        _tableColAlignCenter => 'c',
        comment         => '.\\" \a',
    },

    # --- utmac ----------------------------------------------------------------
    utmac => {
        paragraphOpen   => '.PP',
        title1          => ".\n.H2 \\a",
        title2          => ".\n.H3 \\a",
        title3          => ".\n.H4 \\a",
        title4          => ".PP\n\\*B\\a\\*R\n.br\n",
        title5          => ".PP\n\\*B\\a\\*R",
        blockVerbOpen   => '.PX',
        blockQuoteOpen  => '.PQ',
        fontBoldOpen    => '\*B',
        fontBoldClose   => '\*R',
        fontItalicOpen  => '\*I',
        fontItalicClose => '\*R',
        fontUnderlineOpen  => '\*[underl ',
        fontUnderlineClose => ']',
        fontStrikeOpen  => '\*[strike ',
        fontStrikeClose => ']',
        listItemOpen    => ".PI \n",
        numlistItemOpen => ".PI \\a\n",
        deflistItem1Open => '.PI ',
        bar1            => '.sp 2v',
        bar2            => '.bp',
        anchor          => "\\a\\A\"\\a\"",
        url             => "\\*[url \"\\a\" \"\\a\"]",
        urlMark         => "\\*[url \"\\a\" \"\\a\"]",
        email           => "\\*[mail \"\\a\" \"\\a\"]",
        emailMark       => "\\*[mail \"\\a\" \"\\a\"]",
        img             => "\n.\\\" \\a",
        tableOpen       => ".TS\n~A~~B~tab(^); ~C~.",
        tableClose      => '.TE',
        tableRowOpen    => ' ',
        tableCellSep    => '^',
        _tableAlignCenter  => 'center, ',
        _tableBorder       => 'allbox, ',
        _tableColAlignLeft  => 'l',
        _tableColAlignRight => 'r',
        _tableColAlignCenter => 'c',
        comment         => '.\\" \a',
        blockCommentOpen  => '.ig',
        blockCommentClose => '..',
        pageBreak       => '.bp',
        TOC             => '.XT',
    },

    # --- SPIP -----------------------------------------------------------------
    spip => {
        title1          => '{{{ \a }}}',
        title2          => '<h4>\a</h4>',
        title3          => '<h5>\a</h5>',
        blockVerbOpen   => '<cadre>',
        blockVerbClose  => '</cadre>',
        blockQuoteOpen  => '<quote>',
        blockQuoteClose => '</quote>',
        fontMonoOpen    => '<code>',
        fontMonoClose   => '</code>',
        fontBoldOpen    => '{{',
        fontBoldClose   => '}}',
        fontItalicOpen  => '{',
        fontItalicClose => '}',
        fontUnderlineOpen  => '<u>',
        fontUnderlineClose => '</u>',
        fontStrikeOpen  => '<del>',
        fontStrikeClose => '</del>',
        listItemOpen    => '-',
        listItemLine    => '*',
        numlistItemOpen => '-',
        numlistItemLine => '#',
        bar1            => '----',
        url             => '[->\a]',
        urlMark         => '[\a->\a]',
        email           => '[->\a]',
        emailMark       => '[\a->\a]',
        img             => '<img src="\a" />',
        imgAlignLeft    => '<img src="\a" align="left" />',
        imgAlignRight   => '<img src="\a" align="right" />',
        imgAlignCenter  => '<img src="\a" align="center" />',
        tableTitleRowOpen  => '| {{',
        tableTitleRowClose => '}} |',
        tableTitleCellSep  => '}} | {{',
        tableRowOpen    => '| ',
        tableRowClose   => ' |',
        tableCellSep    => ' | ',
    },

    # --- PageMaker 6 ----------------------------------------------------------
    pm6 => {
        paragraphOpen   => '<@Normal:>',
        title1          => '<@Title1:>\a',
        title2          => '<@Title2:>\a',
        title3          => '<@Title3:>\a',
        title4          => '<@Title4:>\a',
        title5          => '<@Title5:>\a',
        blockVerbOpen   => '<@PreFormat:>',
        blockQuoteLine  => '<@Quote:>',
        fontMonoOpen    => '<FONT "Lucida Console"><SIZE 9>',
        fontMonoClose   => '<SIZE$><FONT$>',
        fontBoldOpen    => '<B>',
        fontBoldClose   => '<P>',
        fontItalicOpen  => '<I>',
        fontItalicClose => '<P>',
        fontUnderlineOpen  => '<U>',
        fontUnderlineClose => '<P>',
        listOpen        => '<@Bullet:>',
        listItemOpen    => "\x95\t",
        numlistOpen     => '<@Bullet:>',
        numlistItemOpen => "\x95\t",
        bar1            => '\a',
        url             => '<U>\a<P>',
        urlMark         => '\a <U>\a<P>',
        email           => '\a',
        emailMark       => '\a \a',
        img             => '\a',
    },

    # --- WikiCreole -----------------------------------------------------------
    creole => {
        title1          => '= \a =',
        title2          => '== \a ==',
        title3          => '=== \a ===',
        title4          => '==== \a ====',
        title5          => '===== \a =====',
        blockVerbOpen   => '{{{',
        blockVerbClose  => '}}}',
        blockQuoteLine  => '  ',
        fontBoldOpen    => '**',
        fontBoldClose   => '**',
        fontItalicOpen  => '//',
        fontItalicClose => '//',
        fontUnderlineOpen  => '//',
        fontUnderlineClose => '//',
        listItemLine    => '*',
        numlistItemLine => '#',
        deflistItem2LinePrefix => ':',
        bar1            => '----',
        url             => '[[\a]]',
        urlMark         => '[[\a|\a]]',
        img             => '{{\a}}',
        tableTitleRowOpen  => '|= ',
        tableTitleRowClose => '|',
        tableTitleCellSep  => ' |= ',
        tableRowOpen    => '| ',
        tableRowClose   => ' |',
        tableCellSep    => ' | ',
    },

    # --- Gemtext (Gemini) -----------------------------------------------------
    gmi => {
        title1          => '# \a ',
        title2          => '## \a ',
        title3          => '### \a ',
        title4          => '### \a ',
        title5          => '### \a ',
        blockVerbLine   => '    ',
        blockQuoteLine  => '> ',
        fontMonoOpen    => '',
        fontMonoClose   => '',
        fontBoldOpen    => '',
        fontBoldClose   => '',
        fontItalicOpen  => '',
        fontItalicClose => '',
        fontUnderlineOpen  => '',
        fontUnderlineClose => '',
        fontStrikeOpen  => '',
        fontStrikeClose => '',
        listItemLine    => '',
        listItemOpen    => '*',
        numlistItemOpen => '*',
        deflistItem1Open => '*',
        bar1            => '```================```',
        bar2            => '```----------------```',
        url             => '=> \a',
        urlMark         => '=> \a \a',
        email           => '\a',
        img             => '=> \a',
        tableTitleRowOpen  => '| ',
        tableTitleRowClose => "|\n|---------------|",
        tableTitleCellSep  => ' |',
        tableRowOpen    => '|',
        tableRowClose   => '|',
        tableCellSep    => ' |',
    },

    # --- BBCode ---------------------------------------------------------------
    bbcode => {
        title1          => '[size=200]\a[/size]',
        title2          => '[size=170]\a[/size]',
        title3          => '[size=150]\a[/size]',
        title4          => '[size=130]\a[/size]',
        title5          => '[size=120]\a[/size]',
        blockQuoteOpen  => '[quote]',
        blockQuoteClose => '[/quote]',
        fontMonoOpen    => '[code]',
        fontMonoClose   => '[/code]',
        fontBoldOpen    => '[b]',
        fontBoldClose   => '[/b]',
        fontItalicOpen  => '[i]',
        fontItalicClose => '[/i]',
        fontUnderlineOpen  => '[u]',
        fontUnderlineClose => '[/u]',
        listOpen        => '[list]',
        listClose       => '[/list]',
        listItemOpen    => '[*]',
        numlistOpen     => '[list=1]',
        numlistClose    => '[/list]',
        numlistItemOpen => '[*]',
        url             => '[url]\a[/url]',
        urlMark         => '[url=\a]\a[/url]',
        img             => '[img]\a[/img]',
    },

    # --- RTF ------------------------------------------------------------------
    rtf => {
        title1          => '~A~{\pard\plain\s11\keepn{\*\txttags title1}\f1\fs24\qc\sb240\sa240\sl480\slmult1\li0\ri0\fi0{\b{\a}}\par}',
        title2          => '~A~{\pard\plain\s12\keepn{\*\txttags title2}\f1\fs24\ql\sb240\sa240\sl480\slmult1\li0\ri0\fi0{\b{\a}}\par}',
        title3          => '~A~{\pard\plain\s13\keepn{\*\txttags title3}\f1\fs24\ql\sb240\sa240\sl480\slmult1\li360\ri0\fi0{\b{\a}}\par}',
        title4          => '~A~{\pard\plain\s14\keepn{\*\txttags title4}\f1\fs24\ql\sb240\sa240\sl480\slmult1\li360\ri0\fi0{\b\i{\a}}\par}',
        title5          => '~A~{\pard\plain\s15\keepn{\*\txttags title5}\f1\fs24\ql\sb240\sa240\sl480\slmult1\li360\ri0\fi0{\i{\a}}\par}',
        numtitle1       => '~A~{\pard\plain\s11\keepn{\*\txttags title1}\f1\fs24\qc\sb240\sa240\sl480\slmult1\li0\ri0\fi0\ls3\ilvl0{\b{\a}}\par}',
        numtitle2       => '~A~{\pard\plain\s12\keepn{\*\txttags title2}\f1\fs24\ql\sb240\sa240\sl480\slmult1\li0\ri0\fi0\ls3\ilvl1{\b{\a}}\par}',
        numtitle3       => '~A~{\pard\plain\s13\keepn{\*\txttags title3}\f1\fs24\ql\sb240\sa240\sl480\slmult1\li360\ri0\fi0\ls3\ilvl2{\b{\a}}\par}',
        numtitle4       => '~A~{\pard\plain\s14\keepn{\*\txttags title4}\f1\fs24\ql\sb240\sa240\sl480\slmult1\li360\ri0\fi0\ls3\ilvl3{\b\i{\a}}\par}',
        numtitle5       => '~A~{\pard\plain\s15\keepn{\*\txttags title5}\f1\fs24\ql\sb240\sa240\sl480\slmult1\li360\ri0\fi0\ls3\ilvl4{\i{\a}}\par}',
        paragraphOpen   => '{\pard\plain\s2{\*\txttags paragraph}\f0\fs24\qj\sb0\sa0\sl480\slmult1\li~D~\ri0\fi360',
        paragraphClose  => '\par}',
        blockVerbOpen   => '{\pard\plain\s3{\*\txttags verbatim}\f2\fs20\ql\sb0\sa240\sl240\slmult1\li720\ri720\fi0',
        blockVerbSep    => '\line',
        blockVerbClose  => '\par}',
        blockQuoteOpen  => '{\pard\plain\s4{\*\txttags quote}\f0\fs24\qj\sb0\sa0\sl480\slmult1\li~D~\ri720\fi0',
        blockQuoteClose => '\par}',
        fontMonoOpen    => '{\f2\fs20{',
        fontMonoClose   => '}}',
        fontBoldOpen    => '{\b{',
        fontBoldClose   => '}}',
        fontItalicOpen  => '{\i{',
        fontItalicClose => '}}',
        fontUnderlineOpen  => '{\ul{',
        fontUnderlineClose => '}}',
        fontStrikeOpen  => '{\strike{',
        fontStrikeClose => '}}',
        anchor          => '{\*\bkmkstart \a}{\*\bkmkend \a}',
        pageBreak       => "\\page\n",
        EOD             => '}',
        url             => '{\field{\*\fldinst{HYPERLINK "\a"}}{\fldrslt{\ul\cf1 \a}}}',
        urlMark         => '{\field{\*\fldinst{HYPERLINK "\a"}}{\fldrslt{\ul\cf1 \a}}}',
        email           => '{\field{\*\fldinst{HYPERLINK "mailto:\a"}}{\fldrslt{\ul\cf1 \a}}}',
        emailMark       => '{\field{\*\fldinst{HYPERLINK "mailto:\a"}}{\fldrslt{\ul\cf1 \a}}}',
        img             => '{\field{\*\fldinst{INCLUDEPICTURE "\a" \\* MERGEFORMAT \\d}}{\fldrslt{(\a)}}}',
        listOpen        => '{\pard\plain\s21{\*\txttags list}\f0\fs24\qj\sb0\sa0\sl480\slmult1',
        listClose       => '}',
        listItemOpen    => "{\*\\listtext{\*\\txttags list indent}\\li~D~\\ri0\\fi-360\\'95\\tab}\\ls1\\ilvl~L~{\*\\txttags list indent}\\li~D~\\ri0\\fi-360\n",
        listItemClose   => '\par',
        numlistOpen     => '{\pard\plain\s21{\*\txttags list}\f0\fs24\qj\sb0\sa0\sl480\slmult1',
        numlistClose    => '}',
        numlistItemOpen => "{\*\\listtext{\*\\txttags list indent}\\li~D~\\ri0\\fi-360 \\a.\\tab}\\ls2\\ilvl~L~{\*\\txttags list indent}\\li~D~\\ri0\\fi-360\n",
        numlistItemClose => '\par',
        deflistOpen     => '{\pard\plain\s21{\*\txttags list}\f0\fs24\qj\sb0\sa0\sl480\slmult1',
        deflistClose    => '}',
        deflistItem1Open  => "{\*\\txttags list indent}\\li~D~\\ri0\\fi-360{\\b\n",
        deflistItem1Close => ':}\tab',
        deflistItem2Open  => '',
        deflistItem2Close => '\par',
        tableOpen       => '{\pard\plain',
        tableClose      => '\par}',
        tableRowOpen    => '{\trowd\trgaph60~A~~B~',
        tableRowClose   => '\row}',
        tableRowSep     => '',
        tableTitleRowOpen  => '{\trowd\trgaph60\trhdr~A~~B~\trbrdrt\brdrs\brdrw20\trbrdrb\brdrs\brdrw20',
        tableTitleRowClose => '',
        tableCellOpen   => '{\intbl\itap1\f0\fs20~A~ ',
        tableCellClose  => '\cell}',
        tableCellHead   => '~B~~S~',
        tableTitleCellOpen  => '{\intbl\itap1\f0\fs20~A~\b ',
        tableTitleCellClose => '\cell}',
        tableTitleCellHead  => '~B~\clbrdrt\brdrs\brdrw20\clbrdrb\brdrs\brdrw20~S~',
        _tableCellColSpan   => '\cellx\a',
        _tableAlignLeft     => '\trql',
        _tableAlignCenter   => '\trqc',
        _tableBorder        => '\trbrdrt\brdrs\brdrw10\trbrdrb\brdrs\brdrw10\trbrdrl\brdrs\brdrw10\trbrdrr\brdrs\brdrw10',
        _tableCellAlignLeft    => '\ql',
        _tableCellAlignRight   => '\qr',
        _tableCellAlignCenter  => '\qc',
        _tableCellBorder       => '\clbrdrt\brdrs\brdrw10\clbrdrb\brdrs\brdrw10\clbrdrl\brdrs\brdrw10\clbrdrr\brdrs\brdrw10',
        bar1            => '{\pard\plain\s1\brdrt\brdrs\brdrw10\li1400\sb120\sa120\ri1400\fs12\par}',
        bar2            => '{\pard\plain\s1\brdrt\brdrs\brdrdb\brdrw10\sb120\sa120\li1400\ri1400\fs12\par}',
    },

    # --- TWiki/Foswiki --------------------------------------------------------
    tml => {
        title1          => '---++ \a',
        title2          => '---+++ \a',
        title3          => '---++++ \a',
        title4          => '---+++++ \a',
        title5          => '---++++++ \a',
        blockVerbOpen   => '<verbatim>',
        blockVerbClose  => '</verbatim>',
        blockQuoteOpen  => '<blockquote>',
        blockQuoteClose => '</blockquote>',
        fontMonoOpen    => '=',
        fontMonoClose   => '=',
        fontBoldOpen    => '*',
        fontBoldClose   => '*',
        fontItalicOpen  => '_',
        fontItalicClose => '_',
        fontUnderlineOpen  => '<u>',
        fontUnderlineClose => '</u>',
        fontStrikeOpen  => '<del>',
        fontStrikeClose => '</del>',
        listItemLine    => '   ',
        listItemOpen    => '* ',
        numlistItemLine => '   ',
        numlistItemOpen => '1. ',
        deflistItem1Open => '$ ',
        deflistItem2Open => ': ',
        bar1            => '---',
        bar2            => '---',
        img             => '<img~A~ src="%ATTACHURL%/\a" border="0" alt="">',
        urlImg          => '[[\a][<img~A~ src="%ATTACHURL%/\a" border="0" alt="">]]',
        _imgAlignLeft   => ' align="left"',
        _imgAlignCenter => ' align="middle"',
        _imgAlignRight  => ' align="right"',
        url             => '[[\a]]',
        urlMark         => '[[\a][\a]]',
        anchor          => "[[#\\a]]\n",
        urlMarkAnchor   => '[[\a][\a]]',
        email           => '\a',
        emailMark       => '[[mailto:\a][\a]]',
        tableRowOpen    => '|',
        tableRowClose   => '|',
        tableTitleCellOpen  => ' *',
        tableTitleCellClose => '* ',
        tableTitleCellSep   => '|',
        tableCellOpen   => ' ',
        tableCellClose  => ' ~S~',
        tableCellSep    => '|',
        _tableCellColSpan => '|',
        comment         => '<!-- \a -->',
        TOC             => '%TOC%',
    },

    # --- mom (groff) ----------------------------------------------------------
    mom => {
        paragraphOpen   => '.PP',
        title1          => ".HEAD \"\\a\"",
        title2          => ".SUBHEAD \"\\a\"",
        title3          => ".SUBSUBHEAD \"\\a\"",
        title4          => ".PP\n.PARAHEAD \"\\a\"",
        title5          => ".PP\n.PARAHEAD \"\\*[UL]\\a\\f[R]\\\"",
        numtitle1       => ".NUMBER_HEADS\n.HEAD \"\\a\"",
        numtitle2       => ".NUMBER_SUBHEADS\n.SUBHEAD \"\\a\"",
        numtitle3       => ".NUMBER_SUBSUBHEADS\n.SUBSUBHEAD \"\\a\"",
        numtitle4       => ".NUMBER_PARAHEADS\n.PP\nPARAHEAD \"\\a\"",
        numtitle5       => ".NUMBER_PARAHEADS\n.PP\n.PARAHEAD \"\\*[UL]\\a\\f[R]\\\"",
        blockVerbOpen   => ".QUOTE\n.CODE",
        blockVerbClose  => ".CODE OFF\n.QUOTE OFF",
        blockQuoteOpen  => '.BLOCKQUOTE',
        blockQuoteClose => '.BLOCKQUOTE OFF',
        fontMonoOpen    => '\f[CR]',
        fontMonoClose   => '\f[]',
        fontBoldOpen    => '\f[B]',
        fontBoldClose   => '\f[]',
        fontItalicOpen  => '\f[I]',
        fontItalicClose => '\f[]',
        fontUnderlineOpen  => '\*[FWD 8p]\*[UL]',
        fontUnderlineClose => '\*[ULX]',
        fontStrikeOpen  => '[\(mi',
        fontStrikeClose => '\(mi]',
        listOpen        => '.LIST BULLET',
        listClose       => '.LIST OFF',
        listItemOpen    => ".ITEM\n",
        numlistOpen     => '.LIST DIGIT',
        numlistClose    => '.LIST OFF',
        numlistItemOpen => ".ITEM\n",
        deflistOpen     => '\# DEF LIST ON',
        deflistClose    => '\# DEF LIST OFF',
        deflistItem1Open  => ".PP\n.PARAHEAD \"",
        deflistItem1Close => ': "',
        bar1            => '.LINEBREAK',
        bar2            => '.NEWPAGE',
        url             => '\a',
        urlMark         => '\a (\a)',
        email           => '\a',
        emailMark       => '\a (\a)',
        img             => ".PSPIC \"\\a\"\n.SHIM\n",
        imgAlignLeft    => ".PSPIC -L \"\\a\"\n.SHIM\n",
        imgAlignCenter  => ".PSPIC \"\\a\"\n.SHIM\n",
        imgAlignRight   => ".PSPIC -R \"\\a\"\n.SHIM\n",
        tableOpen       => ".TS\n~A~~B~tab(^); ~C~.",
        tableClose      => '.TE',
        tableRowOpen    => ' ',
        tableCellSep    => '^',
        _tableAlignCenter   => 'center, ',
        _tableBorder        => 'allbox, ',
        _tableColAlignLeft  => 'l',
        _tableColAlignRight => 'r',
        _tableColAlignCenter => 'c',
        comment         => '\# \a',
        blockCommentOpen  => '.COMMENT',
        blockCommentClose => '.COMMENT OFF',
        TOC             => '.TOC',
        EOD             => '.FINIS',
    },
);

# xhtmls: xhtml base + xhtmls overrides
{
    my %xs = ( %{ $ALL_TAGS{xhtml} }, %{ $ALL_TAGS{xhtmls} } );
    $ALL_TAGS{xhtmls} = \%xs;
}

# html5: xhtml base + html5 overrides
{
    my %h5 = ( %{ $ALL_TAGS{xhtml} }, %{ $ALL_TAGS{html5} } );
    $ALL_TAGS{html5} = \%h5;
}

# htmls: same as html5
$ALL_TAGS{htmls} = { %{ $ALL_TAGS{html5} } };

# wp: xhtml base + wp overrides
{
    my %wp = ( %{ $ALL_TAGS{xhtml} }, %{ $ALL_TAGS{wp} } );
    $ALL_TAGS{wp} = \%wp;
}

# csvs inherits csv
$ALL_TAGS{csvs} = { %{ $ALL_TAGS{csv} } };

# ---------------------------------------------------------------------------
# getTags($config) → hashref
# ---------------------------------------------------------------------------

sub getTags {
    my ($config, $rules) = @_;
    my $target = $config->{target} // '';
    $rules //= {};

    # Normalise alias targets
    my %alias = (
        aap  => 'aat', aas  => 'aat', aatw => 'aat',
        aapw => 'aat', aasw => 'aat', aapp => 'aat',
    );
    $target = $alias{$target} if exists $alias{$target};

    # Zero-initialise all keys
    my %ret = map { $_ => '' } @TAG_KEYS;

    # Layer target-specific tags on top
    if (exists $ALL_TAGS{$target}) {
        my $bank = $ALL_TAGS{$target};
        for my $k (keys %$bank) {
            $ret{$k} = $bank->{$k};
        }
    }

    # Map bar2 → bar1 when bar2 is empty (matches Python getTags behavior)
    if (!$ret{bar2} && $ret{bar1}) {
        $ret{bar2} = $ret{bar1};
    }

    # Map bar2 → pageBreak when mapbar2pagebreak rule is set (Python tags.py)
    if ($rules->{mapbar2pagebreak} && $ret{pageBreak}) {
        $ret{bar2} = $ret{pageBreak};
    }

    return \%ret;
}

# ---------------------------------------------------------------------------
# Exports
# ---------------------------------------------------------------------------
our @EXPORT_OK = qw(getTags);

1;
__END__

=head1 NAME

Text::Txt2tags::Tags - Per-target tag strings for Text::Txt2tags

=head1 SYNOPSIS

  use Text::Txt2tags::Tags qw(getTags);
  my $tags = getTags({ target => 'html' });
  print $tags->{fontBoldOpen};   # <B>

=head1 DESCRIPTION

Port of C<txt2tags3_mod/tags.py> to Perl 5.
Returns a hashref of tag strings (with C<\a> placeholders) for the
requested output target.

=cut
